<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClienteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ["nome" => "Desconhecido", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Prefeitura", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Prefeitura Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Prefeitura Dois irmaos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Prefeitura Lindolfo Collor", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Projeto Viva", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Posto de Saude", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Bradesco", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Banda Mexico Show", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ines Prefeitura", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Departamento Tecnico Prefeitura", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rodrigo Cortume", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Creche Prefeitura", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Romualdo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Centrinho Prefeitura", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Hortencio", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Olidam", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "José Carlos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alcirio", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Uruguaio", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Radio Colorense", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alexandre", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Capivarinha", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Salao - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Mercado economico", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Guido - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ezequiel - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Salao atras socaltur", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Aline - IEI", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cleitmir", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Academia, Fabrica de protetores de lutas", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Batata", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Paulo Mohr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adelio Scherer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Schmier Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lisete Scherer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vilmar ap", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Delmar piscina", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rodrigo Salao", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Roseli - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Andre - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "SJH - escritorio", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cristiane - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Gabriel - Capivarinha", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Julcemar chalé - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vanderlei - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Besing", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lauri", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vilmar gas", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "koop", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Renato Baum", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Policia", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Bras", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Daniel Klein - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jose Franz - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Geraldo Welter - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Airton", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Kern", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcia Metz - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Mariane - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vilma - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Laercio Luft - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Renati - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jair - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Leandor Koch - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ariane - NH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ismael - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "ACZ Contabilidade", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Osmar Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Dolores Losner ", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcelo Machado - CB ", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Junior Dhein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Henke", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Leandro Lamb", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Prédio AP01 - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcelo Welter", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Albano Lamb - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Romeu - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marilucia - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Daiana Riegel - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alexandro - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Oscar Ferrari - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Glaci Beckes - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Clovis Weber - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Sergio Santana - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Teresinha Schneider - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Julio Jacó Prass", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alice Bruch - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Iris Bauerman - LC", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Euclides Kisque - Colombo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Veni Morada do Sol - LC", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Flavio Keller", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jair - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Dirceu Madereira - LC", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Augustinho (Tenente)", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valmor Rambo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Tadeu", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ana Paula", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marlete", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "SIS - Lidiane Fritsch", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vilmar Leonardht", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Albino Diniz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jair Carlos dos Santos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ordeli Borba Becker", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nestor Freitag", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Pedro Osmar Koch", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ursula Ludwig", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Roque Ody", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Claudio Metz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Darli Breuning", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cirlei Soares Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ovidio Franzen", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Joel Bauermann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ernani Gonçalves", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nelsi Klein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cristina Lippert", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Noemia Lippert", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rosane de Melo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Geison Reichert", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Daniel Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Toni Carlos Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Carlos Augusto Leuck", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jonas Holz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Arlei Fritsch", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Livraria - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Gilberto Ody", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Delmar Spindler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Flávio Wust", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "André Mohr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Escola Walter Herman", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valdemar Besing", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Veleda Besing", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Tiago Daniel Fuhr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nelci Maria Fritzen", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Tarcisio Ost", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Liane Meisterlin", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Deisi Maria Schorn", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Martin Zimermann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valdir Augustinho Simon", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Maria Doralice Klein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcos Boys", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Arlindo Becker", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jair Ludwig", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Dirceu Kunradh", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcio Sewald", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Blanca Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Volmir Dietrich", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Edemar Junges", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marilei Junges", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Volnei Abeling", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Claudio Gernhardt", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Geison Maciel", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rogério Weit", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rodrigo - Olidam", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lucia Liane Vagner", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Fernando Holz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adair Ody", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Leandro Schiling", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vereno Francisco - Canova", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Odécio Schneit", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vantuir", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Paulo Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Larissa Wieterkehr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Eloi Robinson", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vilmar Metz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Luis Felipe Schmidt", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Fabiano Krauspenhagen", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Orlando Seth", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Pedro Jorge Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Osmar Mueller", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jaime Plamacol", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Claudir José Holschu", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lauri Trein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vilmar Dietrich", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lygia Terezinha Keller", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valdir Groelin", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adir Cosvino Blauth", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ricardo Roberto Martins", "status_cliente_id" => 1, "usuario_id" => "1"],




        ];

        DB::table('cliente')->insert($data);
    }
}
