<?php

namespace Database\Seeders;

use Exception;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClienteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ["nome" => "Desconhecido", "status_cliente_id" => 1, "usuario_id" => "1"],
<<<<<<< HEAD
=======
            ["nome" => "Prefeitura", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Prefeitura Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Prefeitura Dois irmaos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Prefeitura Lindolfo Collor", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Projeto Viva", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Posto de Saude", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Bradesco", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Banda Mexico Show", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ines Prefeitura", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Departamento Tecnico Prefeitura", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rodrigo Cortume", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Creche Prefeitura", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Romualdo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Centrinho Prefeitura", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Hortencio", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Olidam", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "José Carlos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alcirio", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Uruguaio", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Radio Colorense", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alexandre", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Capivarinha", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Salao - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Mercado economico", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Guido - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ezequiel - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Salao atras socaltur", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Aline - IEI", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cleitmir", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Academia, Fabrica de protetores de lutas", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Batata", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Paulo Mohr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adelio Scherer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Schmier Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lisete Scherer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vilmar ap", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Delmar piscina", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rodrigo Salao", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Roseli - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Andre - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "SJH - escritorio", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cristiane - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Gabriel - Capivarinha", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Julcemar chalé - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vanderlei - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Besing", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lauri", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vilmar gas", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "koop", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Renato Baum", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Policia", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Bras", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Daniel Klein - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jose Franz - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Geraldo Welter - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Airton", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Kern", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcia Metz - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Mariane - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vilma - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Laercio Luft - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Renati - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jair - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Leandor Koch - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ariane - NH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ismael - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "ACZ Contabilidade", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Osmar Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Dolores Losner ", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcelo Machado - CB ", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Junior Dhein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Henke", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Leandro Lamb", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Prédio AP01 - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcelo Welter", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Albano Lamb - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Romeu - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marilucia - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Daiana Riegel - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alexandro - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Oscar Ferrari - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Glaci Beckes - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Clovis Weber - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Sergio Santana - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Teresinha Schneider - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Julio Jacó Prass", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alice Bruch - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Iris Bauerman - LC", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Euclides Kisque - Colombo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Veni Morada do Sol - LC", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Flavio Keller", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jair - Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Dirceu Madereira - LC", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Augustinho (Tenente)", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valmor Rambo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Tadeu", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ana Paula", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marlete", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "SIS - Lidiane Fritsch", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vilmar Leonardht", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Albino Diniz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jair Carlos dos Santos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ordeli Borba Becker", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nestor Freitag", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Pedro Osmar Koch", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ursula Ludwig", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Roque Ody", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Claudio Metz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Darli Breuning", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cirlei Soares Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ovidio Franzen", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Joel Bauermann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ernani Gonçalves", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nelsi Klein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cristina Lippert", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Noemia Lippert", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rosane de Melo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Geison Reichert", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Daniel Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Toni Carlos Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Carlos Augusto Leuck", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jonas Holz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Arlei Fritsch", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Livraria - SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Gilberto Ody", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Delmar Spindler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Flávio Wust", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "André Mohr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Escola Walter Herman", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valdemar Besing", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Veleda Besing", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Tiago Daniel Fuhr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nelci Maria Fritzen", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Tarcisio Ost", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Liane Meisterlin", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Deisi Maria Schorn", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Martin Zimermann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valdir Augustinho Simon", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Maria Doralice Klein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcos Boys", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Arlindo Becker", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jair Ludwig", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Dirceu Kunradh", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcio Sewald", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Blanca Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Volmir Dietrich", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Edemar Junges", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marilei Junges", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Volnei Abeling", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Claudio Gernhardt", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rogério Weit", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rodrigo - Olidam", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lucia Liane Vagner", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Fernando Holz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adair Ody", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Leandro Schiling", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vereno Francisco - Canova", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Odécio Schneit", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vantuir", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Paulo Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Larissa Wieterkehr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Eloi Robinson", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vilmar Metz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Luis Felipe Schmidt", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Fabiano Krauspenhagen", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Orlando Seth", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Pedro Jorge Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Osmar Mueller", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jaime Plamacol", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Claudir José Holschu", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lauri Trein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vilmar Dietrich", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lygia Terezinha Keller", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valdir Groelin", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adir Cosvino Blauth", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ricardo Roberto Martins", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rafael Braz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Leandro Sudback", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Juliana Haag", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lucimara", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Eva Dionisia Schorn", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vanderleia Hepp", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Margarete Klein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Glaci Haupental", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "José Henrique Heilman", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vanice", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adelar Keller (Nene)", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Linha Nova", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Inacio Luft", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valdemir Daniel Bender", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "José Bender", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jorge Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Dalzani Weber", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Inacio Sost", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Miguel Finger", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Elio Nindiger", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Claudio (Pastor)", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Maria Kich", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Carla (Solar)", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nair Fuhr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Leonardht", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Simone Shilling", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "José Heck", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Suane Schorn", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Leandro Hillesheim", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Arsenio Hillesheim", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "José Weschaufelder", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Iara Erbes", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valdemir da Rocha", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Maristela Vandes", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valderi Klein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Junior Kich", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Luis Fernando Medtler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Juazez Rauber", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rafael Luis Koch", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lisete Luisa Rauber", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Pedro Kornelius Filho", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Sérgio Luis Birnfeld", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Luciano Bohden", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "SJH Lado mercado welter", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Roseli Backes", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Solde Seidel (Salgadinho)", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "José Augusto Silveira", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alexandre Reinheimer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Laércio Luft", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Olivio Vogel", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcos Farmacia", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "União Sul Brasileira IASD", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "TopoSinos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Coquinho", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Osmar Scherrer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Genésio Kotlewski", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lojas Taqi", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lauri Becker", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lauren Koch", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jairo Schmitt", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valdir Robinson", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Carla", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rosane Rodrigues", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Irene Medttler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Luis Felipe", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Artur Ervino Metz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rogério Ledur", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marilea Hensel Mattje", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lauri Hass", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Liria Malmann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nelson dos Santos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cleice Withauper", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Armando Stum", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Elio Backes", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adriano Ernesto Weber", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lauricio Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Renato Oto Kleyn", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Carlos Vanzella", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Melita Hofmeister", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Odair Lopes Morais", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ernani Fick", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Angela Hanauer Heck", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rafael Kohl", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Paulo Lenz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Luis Roesler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lidio Boearski", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Bonifacio Graeff", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Décio Teixeira", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Luis Graninstki", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Terezinha Backes", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alexandre Baum", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Iara Aragão", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cirio Fat", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ana Zaleski", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Laurino Klein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Janice Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cesar Schorn", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Canova", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nilton", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Dalice Wurzius", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cornelio Ody", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcelo Di Presente", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Aline e Régis", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Isolde Holler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jones Wathier", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Leandro Gaelzer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "José Lauri Brill", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Elton Messer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcia Lamb", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Elisandro Habitzreuter", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Euzébio Ody", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Carlos Dutra", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cirio Reisner", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Denise Scholl", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Darci Ari Heinz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marli Spindler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcia Weber", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Misael Geareta", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Klauck", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Hilario Guerke", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Beno Schmidt", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Timóteo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Martinho", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rejane Kleyn", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Juan", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Fernando Fardo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vilmar dos Santos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Everaldo (coquinho)", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Odila Peres Funke", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Gilmar", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Sandra Fuhr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcio Fuhr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vilmar Werlang", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valdomiro Franzman", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adriana Fritsch", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jussara Erhardt", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Verônica Soares", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Mariele Robinson", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Andreia Jacob", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Iracema Franken", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Henrique G. Medtler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Anita N Mangold", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Mariceni Kerkoff", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Volmar Nunes Coelho", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adimar Erhart", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jandir Lippert", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rodrigo Nova Vila", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nanci Bauermann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marlei Steffen", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alair Avila", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Verônica", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Milton Claudio Weber", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Sadao Suzuki", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Luciane Rossetti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Tiessa Staudt", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Graciela Golmann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Joacir Krein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valdelirio Schweitzer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Iolanda Jacobsen", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Silvino Kref", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Fabiano Krauspenhar", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Flavio Linck", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jonatas Presser", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Pedro Silva", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lisete Jung", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cristiano Passini", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rubens Schons", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adelar (Nene)", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marli Weber", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alexandre Werle", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Danilo Borcheid", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Delmar Becker", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jorge Coelho", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jeferson Shalemberg", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Gerson Kaiser", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ilstor Martin", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Isolde Maria Kehl", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Tiago Bornsewsky", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcio Jung", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Evanir Kavoqueviz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Andreia dos Santos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jaqueline Borsheid", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Holga N Schmitz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alcides Santos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cedenir Dhein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ari Eckart", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jair Schuster", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "João Henrique Santos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Prefeitura LC", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vitor Krug", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cleomar Althaus", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jaime Roweder", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cleomar Dietrich", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Camara Municipal LC", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "emprestimos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Fabiano", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Terezinha Becker", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "-", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcelo Mueller", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jurandir Lenz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Metz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Newton", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valdir Dapper", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Antonio Kunz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Aline Borcheid", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lidio Boiarski", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Sano sorvetes", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "José dos Santos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Denise Schnem", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Monalisa Staudt", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Auri Francisco Siebert", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Olikleyn", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jandir Mueller", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Elimar Petter Flores", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adriano Weber", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Graciela L W Michel", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jatir Lucas", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Samoel Schmitz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Flavio Catagini", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Leandro", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rubens Agropecuaria", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alcindo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Laci sogra Vilson", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lisete Kreuz Sost", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adriana", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lucio Lanius", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valderi Kleyn", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "ACZ", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Carlos Konzen", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Eliane Farias de Souza", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ariel Hermann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Tata Zaleski", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Moacir", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Anibaldo Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Iara Petry Lippert", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Graciela Messer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Gervasio Pohlmann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adelar Gregorios", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Katharina Pohren", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lucimara Klauck", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valdecir", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Tati", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Sirio Kappaun", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Iane Hanauer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Wilson Sergio", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jorge", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Maristela", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jair V. Mongold", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nelson da Silva", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Delegacia Rec Esta NH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ezequiel", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Antonio Hanzel", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vanderlei Morgenstein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Diego R Weber", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "João Carlos Rodrigues", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "William", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Daniel Rheinheimer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marli Schmitt", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Mario Kipper", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ambrosio Lippert", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valacio Koch", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rita Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Dercio Metz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "João Oscar Klein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Sérgio Habitzreuter", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Fabio Gaelzer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Gerson Werner", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Iara Duarte", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Josemar dos Santos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Liane Eckert", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Odair Franke", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cristina Reinheimer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Luis Simão", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rodrigo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Claci Schutzen", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Erna Scholz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Everson Staudt", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Mariane Schaab", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jeferson Bauermann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jair Luiz Kunst", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ursula Becker", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Janice Gottschalk", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Daniel Froelich", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Almiro Schwingel", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Douglas Pinheiro", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Afonso Donalhausen", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Elton Lang", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ademir Toebe", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Roberto Baron", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Toni Cris Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Telmo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Terezinha L Ody", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lauricio Fuhr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Arnildo Kuhn", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Maria Luiza Prediger", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vilson Taqi", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Julio Korndorsfer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Esc Walter Herrmann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Anderson Fereira", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Tatiana Presser", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Elizando Habitzreuter", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Pref Pres. Lucena", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Brigada Militar LC", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valdir Cornelius", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Francine", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Moacir Nascimento", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ricardo (Galo)", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nazaro Amorin", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Celina Puffal", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Carla Gelinger", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marta de Oliveira", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nolberto Besing", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ana Paula Antunes", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marguit Deifelt", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Daiana Lauck", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Pref Pres. Lucena - Posto", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "SIS", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Edson Machado", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Josias Jacob", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rudinei Alves", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Pastor graça aranha", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Backes SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Deisi Ivoti", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Leticia", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Madereira Morada do Sol", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rosele Bihel Besing", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Pizzaria Engeroff", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Dirso Feldmann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Martin Kleyn", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vanderlei Becker", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jeferson", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Inacio Kerckohff", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Juliano Gemelli", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valdir Leonardht", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Clinidente", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Claudir", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Geisi Salao Studio G", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Clemente Cegelski", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adair Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Liria Schmitt Fuhr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Tionisio Heck", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Flavio Pilar", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Milton Jose Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Elis Lorenzato", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Diego Roberto Borth", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Luis Lauermann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Itamar Both", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Herta Boa Vista", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Renato Tornellis", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Tiago Böde", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Maicon R Bockorni", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Luis Prediger", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Elton pedras", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Gerente M Hercosul", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Schmier Ivotiense", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Joacir José Krein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Mario", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Solange", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jair Inacio Lippert", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Joziela Ody", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Helena Cecilia Utzig", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Laurino Kleyn", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Simoni Graeff", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jader Staudt", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Helena Iracema Anessi", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Miguel Celso Steffler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Tiago Thiesen", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lia Mueller", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nilza Feldmann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Maria B Grohmann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Claudio lado prefeitura", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Maria Luiza Utzig", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Hugo Graeff", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Sidonia Gehm", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Angelo Luis Hagg", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rosemeri Betinger", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valter Zimmermann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jonas", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "João Salécio Borscheid", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Josias", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Diego Diechemann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Sirlei", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Andressa Costa Borscheid", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Solmi Metz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Deivid Peigel", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "João Fernando", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Deisi Weber", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Leonardo Lamb", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Sadi Koch", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Patricia Backes", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cleonice Rohr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rudi Koester", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cristiano Bambert", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Pedro Batista dos Santos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jean Rafael R. dos Santos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Paulo Heller", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Silvio", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valmir Britz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "João Lauri Lippert", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Arci", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ernani Alipio Kunz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Moisés Schmitz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nestor Edmundo Gehm", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Milton Habitzreiter", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "SIS- Maria Pohl", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcio Gregorius", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Edson Maurer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Fabiana Eggers", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ana Jaqueline Heinzen", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Darlan Shossler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nelsa Wiedthauper", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nelson Oleiniczak", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcos Matana", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Noeli Backes", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Aldair dos Santos Rodrigues", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jardim do alto", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Celson Shiling", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nilton Rannow", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Clodomiro Motta", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Arsélio Meisterlin", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Romeu Stofler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lucia Maria Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Carlos Dietrich", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Gaspar Feldmann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marlene Klein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Boré Boa Vista", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Clóvis Carvalho", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Francisco Engel", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vagner Rosa", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Loiva Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Iraci M B Boll", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Delmar Frey", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Joice SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Heinzen SJH", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marli Robinson", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Raul Junior", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jussara Nakaschima", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Milton Schmidt", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Camila Camargo Raimundo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Clovis Hammes", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Djonas Kleyn", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ricardo Eggers", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Arci Zimermann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Mario de Oliveira", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Paulo Martin Becker", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ve Wiedthauger", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Renato Berwian", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nestor Camara Neto", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Flavio Arckmann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Almiro Arckmann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcia da Silva", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Kalinka Rigo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Aline Borscheid", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Kiti Maurer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Melita Xavier", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Zimmermann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Prefeitura PL", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Eliane", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lucia Costa", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jurema Engeroff Stoffel", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Glauco Raimundo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Loiva Becker", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jair Mangold", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcio CDMK", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Thadeu Enzweiler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nazaro Amorim", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adão Pedro Lamb", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jair Gaspar Hillesheim", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jonas Felipe Schmidt", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcelo Azevedo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Sergio F Treixeira", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vani Albino Bauermann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Guido Bruno Schmitz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "João Borscheid (Médicos)", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Evoli Borges", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adriano Molter", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Laercio Airton Sommer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jacinta Engeroff", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Veralice Graeff", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Aline Schwantes", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rafael Huppes", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ivoti Alimentos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Idemar Spaniol", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Claudio Kehl", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jung linha nova", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vera Hanauer Arend", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adriana Wanscher (Lucia Bazar)", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Gisele Souza de Campos (Ezequiel)", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Sandra Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Suzana Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Anderson Freire", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Sergio Schalemberg", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cristiane Dias", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ursula Weber", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valterci Wandscheer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marlene S Breitenbach", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adriano Valdemir Klein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Emater PL", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Adriano Kuhn", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "João Roberto Kuhn", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ilania Maria Dillenburg Berwian", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Sonia Fatima Vagner", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ardete Froehlich", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Pedro Almiro Hillesheim", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Valmir Cezar Miguel", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Maria Doreci Bervian Jung", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Leandro Luiz Castro", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Irene Medtler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Medtler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Luciana Vanderleia Rasch", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Claci Grabin Borosky", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Margaret Klein", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vanderlei Closs", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jacinta Freitag Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Utzig Nova Vila", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "João Leonaldo Panzenhagem", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jessica Weber", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ivo Betinger", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Inacio Britz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Almiro Closs", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Carina Fuhr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcio Michel", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marilei Banham", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Ilse Feiten", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Daiane C Lippert", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Dulce Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marlene Closs", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Mareli Erhart", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marlise Metz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Darci Becker", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Lauri Bauermann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rudi Brandenburg", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Leo Dickel", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Darcy Vogel", "status_cliente_id" => 1, "usuario_id" => "1"],

            ["nome" => "Arnildo Puffal", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Magda Metz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jose Lucio da Silveira", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jose Carlos Caceres", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jones", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Gelson Odacir Pape", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Iane Maria Hanauer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Angelo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Daniela Lauermann", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Pedro Schneider", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Vanduir Metz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Gabriel de Oliveira", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Clóvis Batata", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jorge Mueller", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jair Taqi", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Espeto na Brasa", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Roberto Martins", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Guido Kehl", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marcelo Schramm Jr", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Dirceu Both", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Nesto Gehm", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alesson Goerck", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Danilo Muller", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Prefeitura Presidente Lucena", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Professor Chico", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Kunst Instlações", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rosane", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Kity Froelich", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Delmar Franz", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "RC Mat de Construções", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Francisco Rossi", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "SJH Hanauer", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Alice Bruch", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Darlan Schossler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Freitag pedras", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Iagla", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "SIS-Sabrina dos Passos", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Posto dos Guris", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Dolores Roesler", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Selmar Franco", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Jonatan Vendrusculo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Celio Mahl", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Soeli Dapper da Silva", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Marciel Luis Weber", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Pedro Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Doces Petry", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "José", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Irineu Gnatta", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Rogério Simon", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Daiane", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Cesta Gehm", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Geoclerio Mahl", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "José Agnaldo Baldo", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Janquiel", "status_cliente_id" => 1, "usuario_id" => "1"],
            ["nome" => "Gerson Rauber", "status_cliente_id" => 1, "usuario_id" => "1"],

>>>>>>> 21efa52267019452819bbc85a49598133e4c34b5

        ];

        try {
            DB::table('cliente')->insert($data);
        } catch (Exception $e) {
            echo ($e);
        }
    }
}
